#!/usr/bin/env python3
"""bundle.py — assemble SOVEREIGN-STARTER.md from the source tree.

The friend downloads ONE file. It contains:
  - a short header explaining what this file is and how to use it
  - the full boot-contract starter from docs/BOOT-CONTRACT-STARTER.md
  - an appendix with the empty defect-register template from registry/DEFECTS.md,
    so the friend can copy it into their own registry/DEFECTS.md on setup

Run:
    python3 scripts/bundle.py

Writes SOVEREIGN-STARTER.md to the repo root. Idempotent; safe to run repeatedly.
"""

from __future__ import annotations

import datetime as dt
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTRACT = ROOT / "docs" / "BOOT-CONTRACT-STARTER.md"
REGISTER = ROOT / "registry" / "DEFECTS.md"
OUT = ROOT / "SOVEREIGN-STARTER.md"

HEADER = """<!--
SOVEREIGN-STARTER.md
Generated bundle. Source: https://github.com/EVEglyphDesign/sovereign-starter
Do not edit this file in the source repository — edit docs/BOOT-CONTRACT-STARTER.md
and re-run scripts/bundle.py. In your own repository, edit freely.
-->

# Sovereign Starter — one-file bundle

**What this file is.** A working scaffold for the AI surface that reads your GitHub
repository. Drop it into the root of a new repository, rename it to `README.md`, and
point your AI surface at it.

**What to do with it.**

1. Save this file as `README.md` in the root of a new GitHub repository you control.
2. Open your AI surface (Perplexity, Claude, ChatGPT with GitHub access, or any
   agent that reads a repository) and point it at the file.
3. Read §0 and pick the guided path or the defaults path.
4. Create `registry/DEFECTS.md` from the template in the appendix.

You now have the same operating shape as the surface that produced this file. Your
AI reads it, follows it, and logs its own defects against it. When it delivers, it
runs the check in §4b before it writes the word *delivered*.

---

"""

APPENDIX_HEADER = """
---

## Appendix — `registry/DEFECTS.md` template

Copy the block below into `registry/DEFECTS.md` in your repository on setup. It
carries the schema, the class codes, the standing rule, and one worked example.
Delete the example after you have logged your first real defect, or keep it as
documentation of the shape.

```markdown
"""

APPENDIX_FOOTER = """
```
"""


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def main() -> int:
    if not CONTRACT.exists():
        raise SystemExit(f"bundle: missing source {CONTRACT}")
    if not REGISTER.exists():
        raise SystemExit(f"bundle: missing source {REGISTER}")

    contract_body = CONTRACT.read_text(encoding="utf-8")
    register_body = REGISTER.read_text(encoding="utf-8")

    ts = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    parts = [
        HEADER,
        contract_body,
        APPENDIX_HEADER,
        register_body,
        APPENDIX_FOOTER,
        f"\n---\n\n_Bundle generated {ts}. Source: "
        f"https://github.com/EVEglyphDesign/sovereign-starter._\n",
    ]
    bundle = "".join(parts)
    OUT.write_text(bundle, encoding="utf-8")
    digest = _sha256(bundle)
    print(f"wrote {OUT} ({len(bundle)} bytes, sha256 {digest[:16]}…)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
